name: Build/Test

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  lib-check:
    name: Check libraries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@e60e65a61eb6b7459716e55c7c7f8bc97d6ff02c # 2.2.5
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    needs:
      - lint
      - unit-test
      - lib-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read charmcraft version file
        id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.30-strict/stable
          charmcraft-channel: ${{ steps.charmcraft.outputs.channel }}
          juju-channel: 3/stable
          microk8s-group: snap_microk8s
      - name: Setup MetalLB
        run: |
          sudo microk8s enable metallb:10.64.140.43-10.64.140.49
      - name: Run integration tests
        run: tox -e integration
