name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 1 * * *"
  pull_request:
    paths:
      - .github/workflows/update-libs.yaml

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  charmcraft-channel:
    runs-on: ubuntu-24.04
    outputs:
      channel: ${{ steps.charmcraft.outputs.channel }}
    steps:
    - uses: actions/checkout@v6
    - id: charmcraft
      run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT
  auto-update-libs:
    needs: [charmcraft-channel]
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@main
    secrets: inherit
    with:
      charmcraft-channel: ${{ needs.charmcraft-channel.outputs.channel }}
